/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ceyha
 */
public class AnaPencere extends javax.swing.JFrame {

    Tester test;

    /**
     * Creates new form AnaPencere
     */
    public AnaPencere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        textSerialNumber1 = new javax.swing.JTextField();
        labelSerialNumber1 = new javax.swing.JLabel();
        labelCardType1 = new javax.swing.JLabel();
        labelTestCardID1 = new javax.swing.JLabel();
        textTestCardID1 = new javax.swing.JTextField();
        cardType1 = new javax.swing.JComboBox<>();
        labelDeviceIP1 = new javax.swing.JLabel();
        textDeviceIp1 = new javax.swing.JTextField();
        textServerIp1 = new javax.swing.JTextField();
        labelServerIP1 = new javax.swing.JLabel();
        labelDevicePort1 = new javax.swing.JLabel();
        labelServerPort1 = new javax.swing.JLabel();
        textLocalPort1 = new javax.swing.JTextField();
        textDevicePort1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelSerialNumber = new javax.swing.JLabel();
        textSerialNumber = new javax.swing.JTextField();
        cardType = new javax.swing.JComboBox<>();
        labelCardType = new javax.swing.JLabel();
        labelTestCardID = new javax.swing.JLabel();
        textTestCardID = new javax.swing.JTextField();
        labelDeviceIP = new javax.swing.JLabel();
        textDeviceIp = new javax.swing.JTextField();
        labelServerIP = new javax.swing.JLabel();
        textServerIp = new javax.swing.JTextField();
        labelDevicePort = new javax.swing.JLabel();
        textDevicePort = new javax.swing.JTextField();
        labelServerPort = new javax.swing.JLabel();
        textLocalPort = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teknotolya Cihaz Test Uygulaması");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        textSerialNumber1.setText("K56821234");
        textSerialNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSerialNumber1ActionPerformed(evt);
            }
        });

        labelSerialNumber1.setText("Seri Numarası:");

        labelCardType1.setText("Kart Tipi:");

        labelTestCardID1.setText("Test kart ID:");

        textTestCardID1.setText("01443FBC");
        textTestCardID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTestCardID1ActionPerformed(evt);
            }
        });

        cardType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mifare", "Proxy", "HID Proxy" }));
        cardType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardType1ActionPerformed(evt);
            }
        });

        labelDeviceIP1.setText("Cihaz IP:");

        textDeviceIp1.setText("127.0.0.1");
        textDeviceIp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDeviceIp1ActionPerformed(evt);
            }
        });

        textServerIp1.setText("127.0.0.1");
        textServerIp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textServerIp1ActionPerformed(evt);
            }
        });

        labelServerIP1.setText("Server IP:");

        labelDevicePort1.setText("Cihaz Port:");

        labelServerPort1.setText("Server Port:");

        textLocalPort1.setText("8003");
        textLocalPort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLocalPort1ActionPerformed(evt);
            }
        });

        textDevicePort1.setText("6001");
        textDevicePort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDevicePort1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSerialNumber1)
                            .addComponent(labelCardType1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTestCardID1)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textTestCardID1)
                    .addComponent(cardType1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSerialNumber1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelServerIP1)
                    .addComponent(labelDeviceIP1)
                    .addComponent(labelDevicePort1)
                    .addComponent(labelServerPort1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDeviceIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(textServerIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(textDevicePort1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(textLocalPort1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSerialNumber1)
                    .addComponent(textSerialNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeviceIP1)
                    .addComponent(textDeviceIp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCardType1)
                    .addComponent(labelServerIP1)
                    .addComponent(textServerIp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTestCardID1)
                    .addComponent(textTestCardID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDevicePort1)
                    .addComponent(textDevicePort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServerPort1)
                    .addComponent(textLocalPort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("0901", jPanel1);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelSerialNumber.setText("Seri Numarası:");

        textSerialNumber.setText("K56821234");
        textSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSerialNumberActionPerformed(evt);
            }
        });

        cardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mifare", "Proxy", "HID Proxy" }));
        cardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTypeActionPerformed(evt);
            }
        });

        labelCardType.setText("Kart Tipi:");

        labelTestCardID.setText("Test kart ID:");

        textTestCardID.setText("01443FBC");
        textTestCardID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTestCardIDActionPerformed(evt);
            }
        });

        labelDeviceIP.setText("Cihaz IP:");

        textDeviceIp.setText("127.0.0.1");
        textDeviceIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDeviceIpActionPerformed(evt);
            }
        });

        labelServerIP.setText("Server IP:");

        textServerIp.setText("127.0.0.1");
        textServerIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textServerIpActionPerformed(evt);
            }
        });

        labelDevicePort.setText("Cihaz Port:");

        textDevicePort.setText("6001");
        textDevicePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDevicePortActionPerformed(evt);
            }
        });

        labelServerPort.setText("Server Port:");

        textLocalPort.setText("8003");
        textLocalPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLocalPortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSerialNumber)
                            .addComponent(labelCardType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelTestCardID)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textTestCardID)
                    .addComponent(cardType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSerialNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelServerIP)
                    .addComponent(labelDeviceIP)
                    .addComponent(labelDevicePort)
                    .addComponent(labelServerPort))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDeviceIp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(textServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(textDevicePort, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(textLocalPort, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSerialNumber)
                    .addComponent(textSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeviceIP)
                    .addComponent(textDeviceIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCardType)
                    .addComponent(labelServerIP)
                    .addComponent(textServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTestCardID)
                    .addComponent(textTestCardID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDevicePort)
                    .addComponent(textDevicePort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServerPort)
                    .addComponent(textLocalPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EAC-1746", jPanel2);

        jButton1.setText("Testi Başlat");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textLocalPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLocalPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLocalPortActionPerformed

    private void textDevicePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDevicePortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDevicePortActionPerformed

    private void textServerIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textServerIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textServerIpActionPerformed

    private void textDeviceIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDeviceIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDeviceIpActionPerformed

    private void textTestCardIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTestCardIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTestCardIDActionPerformed

    private void cardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTypeActionPerformed

    private void textSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSerialNumberActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        if (jButton1.getText() == "Testi Başlat") {
            System.out.println("Testi başlat");
            jButton1.setText("Durdur");
            test = new Tester();
        } else {
            System.out.println("Testi durdur");
            jButton1.setText("Testi Başlat");
            test.stopTest();
        }
    }//GEN-LAST:event_jButton1MouseReleased

    private void textSerialNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSerialNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSerialNumber1ActionPerformed

    private void textTestCardID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTestCardID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTestCardID1ActionPerformed

    private void cardType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardType1ActionPerformed

    private void textDeviceIp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDeviceIp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDeviceIp1ActionPerformed

    private void textServerIp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textServerIp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textServerIp1ActionPerformed

    private void textLocalPort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLocalPort1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLocalPort1ActionPerformed

    private void textDevicePort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDevicePort1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDevicePort1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaPencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cardType;
    public static javax.swing.JComboBox<String> cardType1;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel labelCardType;
    public static javax.swing.JLabel labelCardType1;
    public static javax.swing.JLabel labelDeviceIP;
    public static javax.swing.JLabel labelDeviceIP1;
    public static javax.swing.JLabel labelDevicePort;
    public static javax.swing.JLabel labelDevicePort1;
    public static javax.swing.JLabel labelSerialNumber;
    public static javax.swing.JLabel labelSerialNumber1;
    public static javax.swing.JLabel labelServerIP;
    public static javax.swing.JLabel labelServerIP1;
    public static javax.swing.JLabel labelServerPort;
    public static javax.swing.JLabel labelServerPort1;
    public static javax.swing.JLabel labelTestCardID;
    public static javax.swing.JLabel labelTestCardID1;
    public static javax.swing.JTextField textDeviceIp;
    public static javax.swing.JTextField textDeviceIp1;
    public static javax.swing.JTextField textDevicePort;
    public static javax.swing.JTextField textDevicePort1;
    public static javax.swing.JTextField textLocalPort;
    public static javax.swing.JTextField textLocalPort1;
    public static javax.swing.JTextField textSerialNumber;
    public static javax.swing.JTextField textSerialNumber1;
    public static javax.swing.JTextField textServerIp;
    public static javax.swing.JTextField textServerIp1;
    public static javax.swing.JTextField textTestCardID;
    public static javax.swing.JTextField textTestCardID1;
    // End of variables declaration//GEN-END:variables
}
